markdown: rdiscount
pygments: true
permalink: none
sitename: Javascript 标准教程

chapters:
- grammar
- dom 
- htmlapi
- jquery
- tool
- algorithm

grammar: 基本语法
dom: DOM
htmlapi: HTML5 API
algorithm: 算法（Algorithm）
jquery: jQuery
tool: 开发工具
