markdown: rdiscount
pygments: true
permalink: none
sitename: Javascript 标准教程

chapters:
- grammar
- oop
- dom 
- htmlapi
- jquery
- library
- tool
- pattern
- algorithm

grammar: 基本语法
oop: 面向对象编程
dom: DOM
htmlapi: HTML5 API
algorithm: 算法
jquery: jQuery
library: 函数库
pattern: 模式
tool: 开发工具
